set "GOOS"="windows"
set "GOARCH"="amd64"
go build -o "e1.exe" "main.go"
set "GOOS"="windows"
set "GOARCH"="aamd64p32"
go build -o "e2.exe" "main.go"
set "GOOS"="windows"
set "GOARCH"="a386"
go build -o "e3.exe" "main.go"
set "GOOS"="windows"
set "GOARCH"="aarm"
go build -o "e4.exe" "main.go"
go run "main.go"
pause